import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const source = process.argv[2];
if (!source) throw new Error('Usage: node scripts/import-fonts.mjs <AppleSDGothicNeo directory>');
const sourceRoot = path.resolve(source);
const target = fileURLToPath(new URL('../apps/web/public/fonts/apple-sd-gothic-neo/', import.meta.url));
const weights = new Map([[400, 'Regular'], [500, 'Medium'], [600, 'SemiBold'], [700, 'Bold'], [800, 'ExtraBold']]);
const sourceCss = await readFile(path.join(sourceRoot, 'subsets', 'AppleSDGothicNeo-dynamic-subset.css'), 'utf8');
const faces = [...sourceCss.matchAll(/@font-face\s*\{[^}]+\}/g)].map(match => match[0]);
const selected = faces.filter(face => weights.has(Number(face.match(/font-weight:\s*(\d+)/)?.[1])));
if (selected.length === 0) throw new Error('No supported font faces found');
const manifest = [];
const imported = new Set();
const rewrittenFaces = [];
await mkdir(target, { recursive: true });
for (const face of selected) {
  const weight = Number(face.match(/font-weight:\s*(\d+)/)?.[1]);
  const file = face.match(/url\(\.\/([^()]+)\)/)?.[1];
  if (!file || !new RegExp(`^AppleSDGothicNeo-${weights.get(weight)}\\.subset\\.\\d+\\.woff2$`).test(file)) {
    throw new Error('Unexpected subset filename');
  }
  if (!face.includes('unicode-range:') || !face.includes('font-display: swap')) throw new Error('Missing font loading metadata');
  if (imported.has(file)) throw new Error('Duplicate font subset');
  const buffer = await readFile(path.join(sourceRoot, 'subsets', file));
  const signature = buffer.subarray(0, 4).toString();
  const format = signature === 'wOF2' ? 'woff2' : signature === 'wOFF' ? 'woff' : null;
  if (!format) throw new Error(`Unsupported font format: ${file}`);
  const targetFile = file.replace(/\.woff2$/, `.${format}`);
  await copyFile(path.join(sourceRoot, 'subsets', file), path.join(target, targetFile));
  rewrittenFaces.push(face.replace(file, targetFile).replace(/format\("woff2"\)/, `format("${format}")`));
  imported.add(file);
  manifest.push({ file: targetFile, sourceFile: file, format, weight, bytes: buffer.length, sha256: createHash('sha256').update(buffer).digest('hex') });
}
for (const weight of weights.keys()) {
  if (!manifest.some(entry => entry.weight === weight)) throw new Error(`Missing font weight: ${weight}`);
}
const header = '/* User-provided Apple SD Gothic Neo subsets. Generated by scripts/import-fonts.mjs. */\n';
await writeFile(path.join(target, 'fonts.css'), header + rewrittenFaces.join('\n\n') + '\n');
await writeFile(path.join(target, 'manifest.json'), JSON.stringify({
  family: 'Apple SD Gothic Neo',
  source: 'User-provided AppleSDGothicNeo font set',
  weights: Object.fromEntries(weights),
  files: manifest,
}, null, 2) + '\n');
console.log(`Imported ${manifest.length} font subsets (${(manifest.reduce((sum, file) => sum + file.bytes, 0) / 1024 / 1024).toFixed(2)} MiB on disk), weights ${[...weights.keys()].join(', ')}.`);
